#!/bin/bash
set -e
shopt -s inherit_errexit

#start
on_error(){
	echo "[Err] ${BASH_SOURCE[1]}:${BASH_LINENO} - '${BASH_COMMAND}' failed" 1>&2
	exit
}
trap on_error ERR

#guard syntax
if [ -f ./core/conf ]; then echo "It works only when you start it for the first time."; exit; fi
wget
source ./seed
start_up
